Keepup subscriptions
SpineEventEngine/web pull request #154
Opened 2020-10-18 14:02 UTC by YegorUdovchenko

### Summary
This PR brings changes enabling sending of requests for keeping up and cancelling Firebase subscriptions.

The following fixes were made:
 - remove methods of `FirebaseSubscriptionService` making it `run()` and `stop()`. This service now can run and stop itself depending on presence of subscriptions it manages.
 - fix callback notifying subscribers of entity (event) subscriptions, that a subscription is closed. 
 - added integration tests making sure that `/subscription/keep-up` and `/subscription/cancel` requests are sent correctly during a subscription lifecycle.

2020-10-19 08:36 UTC, YegorUdovchenko commented
@dmitrykuzmin PTAL

2020-10-19 08:42 UTC, YegorUdovchenko commented
@dmdashenkov PTAL

2020-10-19 09:54 UTC, dmdashenkov requested changes

2020-10-19 09:54 UTC, dmdashenkov commented on client-js/main/client/firebase-subscription-service.js
> +    return SUBSCRIPTION_KEEP_UP_INTERVAL.inMs();
Let's make this configurable. I think, it is configurable on the server side.

2020-10-19 10:49 UTC, dmitrykuzmin commented on integration-tests/js-tests/test/firebase-client/subscribe-test.js
> +      const topic = client.newTopic()
This can be shortened as
```javascript
return client.subscribeTo(Task).post();
```

2020-10-19 10:49 UTC, dmitrykuzmin commented on client-js/main/client/firebase-subscription-service.js
> +  _keepUpInterval() {
If this method stays unchanged after addressing the @dmdashenkov request, it should be marked `@private` like all others.

2020-10-22 11:10 UTC, YegorUdovchenko commented
@dmitrykuzmin @dmdashenkov PTAL again.

2020-10-22 11:13 UTC, dmdashenkov approved these changes

2020-10-22 11:25 UTC, dmitrykuzmin approved these changes

2020-10-22 11:26 UTC, merged