Prototype `buildSrc/groovy/js/*` scripts in Kotlin
SpineEventEngine/web pull request #173
Opened 2021-11-12 15:57 UTC by yevhenii-nadtochii

This dart is not going to be merged as approved. A separate PR into config repository would be created.

2021-12-01 14:43 UTC, armiol requested changes
24/40 reviewed.

Please see my comments so far.

2021-12-01 14:43 UTC, armiol commented on buildSrc/build.gradle.kts
> +val protobufPluginVersion = "0.8.17"
Let's discuss this one. Either it needs a comment telling to sync this version (similar to `errorProneVersion` below), or we might not need this version at all — as (maybe) we always grab the most recent from Gradle plugin repository.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/JsEnvironment.kt
> +    // A module itself.
Two lines above and two lines below is too much.

Let's try using [the convention we have for Java](https://github.com/SpineEventEngine/SpineEventEngine.github.io/wiki/Java-Code-Style#comment-separators-for-sections-of-the-class), instead.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/JsEnvironment.kt
> + * Information about JavaScript environment.
This is too generic. Smells like browser to me.

How about this:

`Describes the environment in which JavaScript code is assembled and processed during the build.`

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/JsEnvironment.kt
> +     * See [Creating and viewing access tokens | npm Docs](https://docs.npmjs.com/creating-and-viewing-access-tokens)
Let's end all sentences with periods.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/JsEnvironment.kt
> + *  Overriding of "describing" properties leads to inconsistency with expectations. They are not
Please rephrase this section. Something (which probably should tell how "describing" are used, and why they are NOT used by `npm`) is missing.

Also:
```
`npm` tool
```
and 

```
JS
```

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/JsExtension.kt
> + * The main spirit of tasks configuration in this scope is extracting procedural code into
Those who read this won't know anything about "procedural" code. It just does not exist for them anymore. Let's simplify this thought accordingly.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/Idea.kt
> + * Applies and configures an `IDEA` plugin to work with a JavaScript module.
It's either
```
IDEA plugin
```
or 
```
`idea` plugin
```

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/JsPlugins.kt
> + * Supposing, one needs to apply and configure `FooBar` plugin. To achieve that,
```
Let's imagine one wants to apply and configure some `FooBar` plugin. To do that, she needs to go through several steps:

...
```

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/JsPlugins.kt
> + * And how to apply it in `build.gradle.kts`:
`And here's how to ...`

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/McJs.kt
> + * Applies and configures `MsJsPlugin`.
It's `McJsPlugin`.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/Protobuf.kt
> + *  1. Specifies `protoc` compiler;
What do you mean? "Configures"? 

Let's discuss this if you need.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/plugin/Protobuf.kt
> +                    remove("java")
I think this step may have unwanted consequences. At this point we don't know whether Java is required.

Let's discuss if needed.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Assemble.kt
> +
Please kill.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Assemble.kt
> + * This is a lifecycle task that performs no action itself. It is used to aggregate other tasks
Let's settle down. Either it "performs no action itself" or  "compiles Protobuf messages".

Right now the whole text looks a copy-paste mistake. Please adjust.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Assemble.kt
> + * The task installs a package and any packages that it depends on using the `npm install` command.
I don't understand this part: "installs a package and any packages that it depends on". There is no certain "package" in this context. Therefore, there's nothing to speak of.

Please rephrase.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Check.kt
> + *  @param configuration any additional configuration related to the module's verifying.
Did you mean "verification"?

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Check.kt
> +
Let's not have so many empty lines. There are of no use.

2021-12-01 14:43 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/javascript/task/Check.kt
> +
Same here. 

Please review the changeset for this issue.

2021-12-01 17:01 UTC, armiol reviewed
Please see another portion of the comments.

2021-12-07 09:51 UTC, armiol commented
@yevhenii-nadtochii LGTM. Let's do this one more time, starting from `config`.

2021-12-07 14:18 UTC, yevhenii-nadtochii commented
Closing this draft as it's approved and an associated PR into `config` repository is created.
See [Migrate `buildSrc/groovy/js/*` scripts to Kotlin](https://github.com/SpineEventEngine/config/pull/308)

2021-12-07 14:18 UTC, closed without merging