Update copyright
SpineEventEngine/web pull request #200
Opened 2023-05-15 14:44 UTC by ndolhii

Change year in copyright headers `2022` -> `2023`.

2023-05-16 13:30 UTC, nick-dolgiy commented
@armiol PTAL.

2023-05-17 09:47 UTC, armiol requested changes
Please run the local build, so that the JS artifact version is updated in respective files as well.

2023-05-17 13:18 UTC, nick-dolgiy commented
@armiol PTAL.

2023-05-17 13:20 UTC, armiol approved these changes

2023-05-17 13:33 UTC, merged